MyTableau/urls.py
# -*-coding: utf-8 -*-
# staticfiles_urlpatterns是指当部署到本地非django内置服务器时，
# django要主动去检查STATICFILE的设定
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import patterns, include, url
from MyTableau import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'MyTableau.views.home', name='home'),
    # url(r'^MyTableau/', include('MyTableau.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', 			views.index),
    url(r'^pretest/$', 	views.pretest),
    url(r'^admin/', 	include(admin.site.urls)),
    url(r'^account/', 	include('account.url')),
    url(r'^widget/', 	include('widget.url', namespace="widget")),
    url(r'^scene/', 	include('scene.url', namespace="scene")),
    url(r'^theme/', 	include('theme.url', namespace="theme")),
    url(r'^skin/',      include('skin.url')),
    url(r'^connect/',   include('connect.url')),
    url(r'^monitor/',   include('monitor.url')),
    url(r'^ws/',        include('websocket.url')),
)
urlpatterns += staticfiles_urlpatterns()

widget/forms.py
# encoding: utf-8
from django import forms

class ConnDbForm(forms.Form):
	ip			= forms.GenericIPAddressField(initial='10.1.50.96')
	port		= forms.IntegerField(max_value=65535, min_value=0, required=False, initial='5432')
	db			= forms.CharField(initial='data_insight')
	user		= forms.CharField(initial='postgres')
	pwd			= forms.CharField(widget=forms.PasswordInput())

templates/widget/widget_add/assets/js/region/table/template/dialog_choosed_db.html
<script type="text/template">
<div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="choosed_db_title">新建连接到数据库</h4>
      </div>

      <div class="modal-body">
      	<div class="bs-example bs-example-tabs">
		    <ul id="choosed_db_tab" class="nav nav-tabs" role="tablist">
		      <li class="active"><a href="#choosed_db" role="tab" data-toggle="tab">建立新的连接</a></li>
		      <li class=""><a href="#choosed_history" role="tab" data-toggle="tab">连接到历史数据源</a></li>
		    </ul>
		    <div class="tab-content">
		      <div class="tab-pane fade active in" id="choosed_db">
		        <ul class="choosed-db-new">
			        <li data-name="mysql"><span class="glyphicon glyphicon-book"></span>mysql</li>
			        <li data-name="oracle"><span class="glyphicon glyphicon-book"></span>oracle</li>
			        <li data-name="postgres"><span class="glyphicon glyphicon-book"></span>postgres</li>
			        <li data-name="mongdb"><span class="glyphicon glyphicon-book"></span>mongdb</li>
			        <li data-name="sql server"><span class="glyphicon glyphicon-book"></span>sql server</li>
			        <li data-name="sqlsite"><span class="glyphicon glyphicon-book"></span>sqlsite</li>
		        </ul>
		      </div>
		      <div class="tab-pane fade" id="choosed_history">
		        <ul class="choosed-db-old">
			        <li><span class="glyphicon glyphicon-tasks"></span>历史数据源1</li>
			        <li><span class="glyphicon glyphicon-tasks"></span>历史数据源2</li>
			        <li><span class="glyphicon glyphicon-tasks"></span>历史数据源3</li>
			        <li><span class="glyphicon glyphicon-tasks"></span>历史数据源4</li>
			        <li><span class="glyphicon glyphicon-tasks"></span>历史数据源5</li>
			        <li><span class="glyphicon glyphicon-tasks"></span>历史数据源6</li>
		        </ul>
		      </div>
		    </div>
  		</div>
      </div>

</div>
</script>

templates/widget/widget_add/assets/js/region/table/template/dialog_connect_db.html
<script type="text/template">
<div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="connect_db_title">新建连接到数据库  [<%= kind %>]</h4>
      </div>

      <div class="modal-body">
			<div id="connect_db_form">
				<p>
					<label for="id_ip">Ip:</label> 
					<input id="connect_ip" name="ip" type="text" value="<%= ip %>">
				</p>
				<p>
					<label for="id_port">Port:</label> 
					<input id="connect_port" max="65535" min="0" name="port" type="number" value="<%= port %>">
				</p>
				<p>
					<label for="id_db">Db:</label> 
					<input id="connect_db" name="db" type="text" value="<%= db %>">
				</p>
				<p>
					<label for="id_user">User:</label> 
					<input id="connect_user" name="user" type="text" value="<%= user %>">
				</p>
				<p>
					<label for="id_pwd">Pwd:</label> 
					<input id="connect_pwd" name="pwd" type="password">
				</p>
				<input id="connect_kind" type="hidden" value="<%= kind %>" />
			</div>
      </div>

      <div class="modal-footer">
      	<div id="connect_error">连接失败，请检查上面参数是否正确！</div>
      	<button type="button" class="connect-db-commit btn btn-primary">连接</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
      </div>

</div>
</script>

templates/widget/widget_add/assets/js/region/table/template/dialog_import_file.html
<script type="text/template">
<div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="new_table_title">通过数据文件导入数据</h4>
      </div>

      <div class="modal-body">
      		<div id="import_file_form">
				<p>
					<label>文件：</label> 
					<input id="importfile" name="file" type="file">
				</p>
				<p>
					<label>类型：</label> 
					<select id="import_file_type">
						<option value="csv">csv</option>
						<option value="xlsx">excel</option>
					</select>
				</p>
				<p>
					<label>首行包含列名：</label> 
					<select id="import_file_attr">
						<option value="1">是</option>
						<option value="0">否</option>
					</select>
				</p>
				<p>
					<label>编码：</label> 
					<select id="import_file_code">
						<option value="UTF-8">UTF-8</option>
						<option value="UTF-16">UTF-16</option>
						<option value="GBK">GBK</option>
						<option value="GBK2312">GBK2312</option>
						<option value="ASCII">ASCII</option>
					</select>
				</p>
			</div>
      </div>

       <div class="modal-footer">
        <div class="import-file-tip">请选择文件！</div>
      	<button type="button" class="import-file-commit btn btn-primary">确定</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
      </div>
</div>
</script>

templates/widget/widget_add/assets/js/region/table/template/dialog_new_table.html
<script type="text/template">
<div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="new_table_title">新建数据表</h4>
      </div>

      <div class="modal-body">
        <p>请选择新建数据表的方式：</p>
        <div class="dialog-new-table-content clearfix">
        	<div class="dialog-new-table-db"><p>通过连接第三方数据库</p><p>（需要输入账号密码）</p></div>
        	<div class="dialog-new-table-file"><p>通过导入数据文件</p><p>(csv,excel等)</p></div>
        </div>
      </div>
</div>
</script>

templates/widget/widget_add/assets/js/region/table/template/dialog_table_manage.html
<script type="text/template">
<div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="table_manage_title">数据表管理</h4>
      </div>

      <div class="modal-body table-manage-content clearfix">
      <p id="table_manage_new"><a href="#">新建数据表</a></p>
      <ul id="table_manage_ul">
      <% _.each(items, function(item){ %>
           <li><input data-id="<%= item.id %>" class="manageCheckbox" type="checkbox" <% if(item.selected) { %> checked="true" <% } %> /><%= item.tableName %></li>
      <% }); %>
      </ul>
      </div>

      <div class="modal-footer">
      <div class="table-manage-operate">
      	<a class="table-manage-all" href="#">全选</a>
      	<a class="table-manage-none" href="#">全不选</a>
      </div>
      	<button type="button" class="btn btn-primary table-manage-commit">确定</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
      </div>

</div>
</script>

templates/widget/widget_add/assets/js/region/table/template/region_table.html
<script>
	<div id="table_template_header" class="panel-heading">数据表<span class="glyphicon glyphicon-new-window"></span></div>
	<ul id="table_template_content">
	 <% _.each(items, function(item){ %>
	 	 <% if(item.selected) { %>
	 	 	<% if(item.choosed) { %>
             <li class="table-item table-item-choosed" data-table="<%= item.tableName %>" data-id="<%= item.id %>"><%= item.tableName %></li>
             <% }else { %>
             	<li class="table-item"  data-table="<%= item.tableName %>" data-id="<%= item.id %>"><%= item.tableName %></li>
             <% } %>
         <% } %>
    <% }); %>
	</ul>
</script>